### PR TITLE
fix: tiktok gift variation coins does not send as value

### PR DESCRIPTION
**Pull request by abdevlpr**

### CODE REVIEW

**Review by ahadcove — APPROVED** [review]

**Comment by Shakeel9410** [comment]
> _ No description provided. _

pls i am waiting from your response

**Comment by abdevlpr** [comment]
@Shakeel9410 Hello, have a nice day! could you please be more specific what is this software and how would you use it with Lumia Stream

**Comment by abdevlpr** [comment]
> > _ No description provided. _
> 
> pls i am waiting from your response

@Shakeel9410

**Comment by Shakeel9410** [comment]
Brother i want to purchase tiktok coin If you have such a platform, can you
confirm me Github I have seen on hand that either software application is
available Or is there any platform available from which I can purchase at a
lower price?

SHAKEEL AHMAD

**Comment by Shakeel9410** [comment]
i know brother i want to you tool and softwear and any kind of this

**Pull request merged**
